// Mock data for Commissions

export const mockCommissions = [
  {
    id: "comm-001",
    partnerId: "partner-001",
    partnerName: "Sunil Verma",
    investmentId: "inv-001",
    productName: "Premium Growth Plan",
    investorId: "investor-001",
    investorName: "Anil Desai",
    investmentAmount: 500000,
    commissionRate: 2.5,
    commissionAmount: 12500,
    status: "paid",
    paidDate: "2024-08-20",
    paymentMethod: "Bank Transfer",
    transactionId: "TXN-COMM-001",
  },
  {
    id: "comm-002",
    partnerId: "partner-001",
    partnerName: "Sunil Verma",
    investmentId: "inv-003",
    productName: "Premium Growth Plan",
    investorId: "investor-002",
    investorName: "Kavita Nair",
    investmentAmount: 300000,
    commissionRate: 2.5,
    commissionAmount: 7500,
    status: "paid",
    paidDate: "2024-10-15",
    paymentMethod: "Bank Transfer",
    transactionId: "TXN-COMM-002",
  },
  {
    id: "comm-003",
    partnerId: "partner-002",
    partnerName: "Meera Singh",
    investmentId: "inv-004",
    productName: "Lump Sum Maturity Plan",
    investorId: "investor-003",
    investorName: "Rohit Malhotra",
    investmentAmount: 5000000,
    commissionRate: 3.5,
    commissionAmount: 175000,
    status: "pending",
    paidDate: null,
    paymentMethod: null,
    transactionId: null,
  },
]
