// Mock data for Investments

export const mockInvestments = [
  {
    id: "inv-001",
    investorId: "investor-001",
    investorName: "Anil Desai",
    investorEmail: "anil.desai@example.com",
    productId: "prod-001",
    productName: "Premium Growth Plan",
    productType: "Installment",
    amount: 500000,
    date: "2024-08-15",
    status: "active",
    expectedReturns: 72000,
    nextPayout: "2025-02-15",
    planId: "PLAN-001",
    paymentMethod: "Bank Transfer",
    transactionId: "TXN-001",
    paymentDate: "2024-08-15",
    paymentStatus: "completed",
  },
  {
    id: "inv-002",
    investorId: "investor-001",
    investorName: "Anil Desai",
    investorEmail: "anil.desai@example.com",
    productId: "prod-002",
    productName: "Hybrid Investment Plan",
    productType: "Hybrid",
    amount: 1000000,
    date: "2024-09-01",
    status: "active",
    expectedReturns: 290000,
    nextPayout: "2025-03-01",
    planId: "PLAN-002",
    paymentMethod: "UPI",
    transactionId: "TXN-002",
    paymentDate: "2024-09-01",
    paymentStatus: "completed",
  },
  {
    id: "inv-003",
    investorId: "investor-002",
    investorName: "Kavita Nair",
    investorEmail: "kavita.nair@example.com",
    productId: "prod-001",
    productName: "Premium Growth Plan",
    productType: "Installment",
    amount: 300000,
    date: "2024-10-10",
    status: "active",
    expectedReturns: 43200,
    nextPayout: "2025-04-10",
    planId: "PLAN-003",
    paymentMethod: "Bank Transfer",
    transactionId: "TXN-003",
    paymentDate: "2024-10-10",
    paymentStatus: "completed",
  },
  {
    id: "inv-004",
    investorId: "investor-003",
    investorName: "Rohit Malhotra",
    investorEmail: "rohit.malhotra@example.com",
    productId: "prod-003",
    productName: "Lump Sum Maturity Plan",
    productType: "Lump-sum",
    amount: 5000000,
    date: "2024-11-20",
    status: "pending",
    expectedReturns: 2250000,
    nextPayout: null,
    planId: "PLAN-004",
    paymentMethod: "Bank Transfer",
    transactionId: "TXN-004",
    paymentDate: null,
    paymentStatus: "pending",
  },
]
