// Mock data for Payouts

export const mockPayouts = [
  {
    id: "payout-001",
    investorId: "investor-001",
    investorName: "Anil Desai",
    investmentId: "inv-001",
    productName: "Premium Growth Plan",
    amount: 6000,
    dueDate: "2025-02-15",
    status: "pending",
    crnNumber: null,
    processedDate: null,
    bankAccount: "****1234",
    transactionId: null,
  },
  {
    id: "payout-002",
    investorId: "investor-001",
    investorName: "Anil Desai",
    investmentId: "inv-002",
    productName: "Hybrid Investment Plan",
    amount: 10000,
    dueDate: "2025-03-01",
    status: "pending",
    crnNumber: null,
    processedDate: null,
    bankAccount: "****1234",
    transactionId: null,
  },
  {
    id: "payout-003",
    investorId: "investor-002",
    investorName: "Kavita Nair",
    investmentId: "inv-003",
    productName: "Premium Growth Plan",
    amount: 3600,
    dueDate: "2025-01-10",
    status: "processed",
    crnNumber: "CRN-20250110-001",
    processedDate: "2025-01-10",
    bankAccount: "****5678",
    transactionId: "TXN-PAY-001",
  },
  {
    id: "payout-004",
    investorId: "investor-001",
    investorName: "Anil Desai",
    investmentId: "inv-001",
    productName: "Premium Growth Plan",
    amount: 6000,
    dueDate: "2025-01-15",
    status: "processed",
    crnNumber: "CRN-20250115-002",
    processedDate: "2025-01-15",
    bankAccount: "****1234",
    transactionId: "TXN-PAY-002",
  },
]
