// Mock data for Products

export const mockProducts = [
  {
    id: "prod-001",
    name: "Premium Growth Plan",
    type: "Installment",
    status: "active",
    minInvestment: 100000,
    maxInvestment: 5000000,
    duration: 12,
    commissionRate: 2.5,
    description: "Monthly returns with flexible investment options",
    returnStructure: {
      monthlyReturn: 1.2,
      totalReturn: 14.4,
    },
    totalInvestments: 45,
    totalVolume: 12500000,
    averageInvestment: 277778,
    activeInvestments: 38,
  },
  {
    id: "prod-002",
    name: "Hybrid Investment Plan",
    type: "Hybrid",
    status: "active",
    minInvestment: 500000,
    maxInvestment: 10000000,
    duration: 24,
    commissionRate: 3.0,
    description: "Combination of monthly returns and maturity bonus",
    returnStructure: {
      monthlyReturn: 1.0,
      maturityBonus: 5.0,
      totalReturn: 29.0,
    },
    totalInvestments: 28,
    totalVolume: 18500000,
    averageInvestment: 660714,
    activeInvestments: 25,
  },
  {
    id: "prod-003",
    name: "Lump Sum Maturity Plan",
    type: "Lump-sum",
    status: "active",
    minInvestment: 1000000,
    maxInvestment: 20000000,
    duration: 36,
    commissionRate: 3.5,
    description: "Single investment with maturity returns",
    returnStructure: {
      maturityReturn: 45.0,
    },
    totalInvestments: 15,
    totalVolume: 22000000,
    averageInvestment: 1466667,
    activeInvestments: 12,
  },
]
